ALTER TABLE meetings ADD COLUMN IF NOT EXISTS end_date_time VARCHAR(50);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS deadline VARCHAR(50);

ALTER TABLE meeting_participants ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'pending';
