ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar VARCHAR(500) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS description VARCHAR(1000) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS contacts TEXT DEFAULT NULL;
